models:
- name: mpt-7b-8k-chat
  backend: leapfrog-01:50051
- name: all-MiniLM-L6-v2
  backend: localhost:50051
- name: whisper
  backend: localhost:50051
- name: ctransformers
  backend: localhost:50051
rag:
  vector_stores:
    - weaviate
    - chromadb
  file_extensions:
    - pdf
    - txt
  llm:
    hub: huggingface
    model: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  embed_model:
    hub: huggingface
    model: "BAAI/bge-small-en-v1.5"
