[project]
name = "leapfrogai-api"
version = "0.4.0"
dependencies = ["fastapi >= 0.103.1"]
requires-python = ">=3.11"

[project.optional-dependencies]
dev = ["pip-tools", "pytest"]

[tool.pip-tools]
generate-hashes = true
