{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: leapfrogai
spec:
  gateways:
  - istio-system/{{ .Values.istio.gateway }}
  hosts:
  - {{ .Values.domain }}
  http:
   - match:
     - uri:
         prefix: "###ZARF_VAR_PREFIX###/"
     rewrite:
       uri: "/"
     route:
     - destination:
        host: api
        port:
          number: 8080
   - match:
       - uri:
           prefix: "###ZARF_VAR_PREFIX###"
     redirect:
       uri: "###ZARF_VAR_PREFIX###/"
{{- end }}
---