name: Run tests
on: [push, pull_request]

jobs:
  Run-Tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'
      - run: make requirements-dev requirements
      - run: make test