name: lint
on: [pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Validate Lint
        uses: chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4 # v1.0.0
        with:
          version: 0.2.2

      - name: Validate Formatting
        uses: chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4 # v1.0.0
        with:
          version: 0.2.2
          args: format --check

      # Install python so we can validate the requirements.txt files are up to date
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c #v5.0.0
        with:
          python-version-file: 'pyproject.toml'

      - name: Validate Requirement Files Updated
        run: |
          python -m pip install pip-tools==7.3.0
          make build-requirements build-requirements-dev
          git diff --exit-code
