name: Publish Artifacts 

on:
  push:
    tags:
      - "*"

jobs:
  zarf:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build API Image
      run: make docker-build docker-push VERSION=$GITHUB_REF_NAME

    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main

    - name: Build Zarf Package
      run: zarf package create . --confirm

    - name: Publish Zarf Package
      run: zarf package publish zarf-package-*.zst oci://ghcr.io/defenseunicorns/packages