name: Test API
on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'
          cache: 'pip'

      - name: Install Python Deps
        run: pip install -r requirements-dev.txt
     
      - name: Run Pytest
        run: python -m pytest . -v