name: Test Package Deployment
on:
  pull_request

jobs:
  e2e-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@f95763914e20e493bb5d45d63e30e17138f981d6 # v1.0.0
        with:
          download-init-package: true

      - name: Login to Registry1
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: Build leapfrogai image
        run: make docker-build VERSION=local

      - name: Build leapfrogai zarf package
        run: make zarf-build VERSION=local

      - name: Install UDS-CLI
        run: |
          wget https://github.com/defenseunicorns/uds-cli/releases/download/v0.9.2/uds-cli_v0.9.2_Linux_amd64
          chmod +x uds-cli_v0.9.2_Linux_amd64
          sudo mv uds-cli_v0.9.2_Linux_amd64 /usr/local/bin/uds

      - name: Setup K3D
        run: |
          uds deploy k3d-core-istio-dev:0.12.0

      - name: Deploy LFAI Package 
        run: zarf package deploy zarf-package-leapfrogai-api-amd64*.tar.zst --confirm

      - name: Debug Deployment
        run: |
          zarf package list
          zarf connect list
          





